//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.05 at 01:16:56 PM IST 
//


package com.dhl.dhltalentlinkapp.utils;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dhl.dhltalentlinkapp.outbound.dao.export.sdh package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dhl.dhltalentlinkapp.outbound.dao.export.sdh
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DATADS }
     * 
     */
    public DATADS createDATADS() {
        return new DATADS();
    }

    /**
     * Create an instance of {@link DATADS.G1 }
     * 
     */
    public DATADS.G1 createDATADSG1() {
        return new DATADS.G1();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 }
     * 
     */
    public DATADS.G1 .G2 createDATADSG1G2() {
        return new DATADS.G1 .G2();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT createDATADSG1G2FILEFRAGMENT() {
        return new DATADS.G1 .G2 .FILEFRAGMENT();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2Synch() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorker() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PayrollRelationshipEmployee }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PayrollRelationshipEmployee createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerPayrollRelationshipEmployee() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PayrollRelationshipEmployee();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PayrollRelationshipEmployee.PayrollCostAttributes }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PayrollRelationshipEmployee.PayrollCostAttributes createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerPayrollRelationshipEmployeePayrollCostAttributes() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PayrollRelationshipEmployee.PayrollCostAttributes();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PayrollRelationshipEmployee.AssignmentElementEntries }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PayrollRelationshipEmployee.AssignmentElementEntries createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerPayrollRelationshipEmployeeAssignmentElementEntries() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PayrollRelationshipEmployee.AssignmentElementEntries();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.AssignmentSalary }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.AssignmentSalary createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerAssignmentSalary() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.AssignmentSalary();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.Termination }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.Termination createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerTermination() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.Termination();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationship() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.Location }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.Location createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipLocation() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.Location();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipDottedLineManager() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipDottedLineManagerDottedLineManagerPersonNumber() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber.DottedLineManagerEmail }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber.DottedLineManagerEmail createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipDottedLineManagerDottedLineManagerPersonNumberDottedLineManagerEmail() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber.DottedLineManagerEmail();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber.DottedLineManagerGID }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber.DottedLineManagerGID createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipDottedLineManagerDottedLineManagerPersonNumberDottedLineManagerGID() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber.DottedLineManagerGID();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipSupervisorManager() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerPersonNumber }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerPersonNumber createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipSupervisorManagerSupervisorManagerPersonNumber() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerPersonNumber();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerPersonNumber.ContractSupervisorGID }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerPersonNumber.ContractSupervisorGID createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipSupervisorManagerSupervisorManagerPersonNumberContractSupervisorGID() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerPersonNumber.ContractSupervisorGID();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.AssignmentSourceKeyBlock }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.AssignmentSourceKeyBlock createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipAssignmentSourceKeyBlock() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.AssignmentSourceKeyBlock();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonInfoName }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonInfoName createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerPersonInfoName() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonInfoName();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonGID }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonGID createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerPersonGID() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonGID();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonInfoDetail }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonInfoDetail createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerPersonInfoDetail() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonInfoDetail();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Parameters }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Parameters createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchParameters() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Parameters();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonAddress }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonAddress createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerPersonAddress() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonAddress();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonEmailDetail }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonEmailDetail createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerPersonEmailDetail() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonEmailDetail();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonPhoneDetail }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonPhoneDetail createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerPersonPhoneDetail() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonPhoneDetail();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PayrollRelationshipEmployee.PayrollCostAttributes.PayrollCostAttributesDetails }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PayrollRelationshipEmployee.PayrollCostAttributes.PayrollCostAttributesDetails createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerPayrollRelationshipEmployeePayrollCostAttributesPayrollCostAttributesDetails() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PayrollRelationshipEmployee.PayrollCostAttributes.PayrollCostAttributesDetails();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PayrollRelationshipEmployee.AssignmentElementEntries.ElementEntriesDetails }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PayrollRelationshipEmployee.AssignmentElementEntries.ElementEntriesDetails createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerPayrollRelationshipEmployeeAssignmentElementEntriesElementEntriesDetails() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PayrollRelationshipEmployee.AssignmentElementEntries.ElementEntriesDetails();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.AssignmentSalary.AssignmentSalaryDetail }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.AssignmentSalary.AssignmentSalaryDetail createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerAssignmentSalaryAssignmentSalaryDetail() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.AssignmentSalary.AssignmentSalaryDetail();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.Termination.TerminationDetails }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.Termination.TerminationDetails createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerTerminationTerminationDetails() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.Termination.TerminationDetails();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.AssignmentDetail }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.AssignmentDetail createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipAssignmentDetail() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.AssignmentDetail();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.HRBusinessPartner }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.HRBusinessPartner createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipHRBusinessPartner() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.HRBusinessPartner();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.CompAndBensRepresentative }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.CompAndBensRepresentative createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipCompAndBensRepresentative() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.CompAndBensRepresentative();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SocialPartnerRepresentative }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SocialPartnerRepresentative createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipSocialPartnerRepresentative() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SocialPartnerRepresentative();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.PositionStartDate }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.PositionStartDate createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipPositionStartDate() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.PositionStartDate();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.Location.LocationDetail }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.Location.LocationDetail createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipLocationLocationDetail() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.Location.LocationDetail();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerDetails }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerDetails createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipDottedLineManagerDottedLineManagerDetails() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerDetails();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber.PersonManager }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber.PersonManager createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipDottedLineManagerDottedLineManagerPersonNumberPersonManager() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber.PersonManager();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber.DottedLineManagerEmail.DottedLineManagerEmailDetail }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber.DottedLineManagerEmail.DottedLineManagerEmailDetail createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipDottedLineManagerDottedLineManagerPersonNumberDottedLineManagerEmailDottedLineManagerEmailDetail() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber.DottedLineManagerEmail.DottedLineManagerEmailDetail();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber.DottedLineManagerGID.DottedLineManagerGIDDetails }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber.DottedLineManagerGID.DottedLineManagerGIDDetails createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipDottedLineManagerDottedLineManagerPersonNumberDottedLineManagerGIDDottedLineManagerGIDDetails() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.DottedLineManager.DottedLineManagerPersonNumber.DottedLineManagerGID.DottedLineManagerGIDDetails();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerDetails }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerDetails createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipSupervisorManagerSupervisorManagerDetails() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerDetails();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerPersonNumber.OrganizationManager }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerPersonNumber.OrganizationManager createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipSupervisorManagerSupervisorManagerPersonNumberOrganizationManager() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerPersonNumber.OrganizationManager();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerPersonNumber.SupervisorManagerEmail }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerPersonNumber.SupervisorManagerEmail createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipSupervisorManagerSupervisorManagerPersonNumberSupervisorManagerEmail() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerPersonNumber.SupervisorManagerEmail();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerPersonNumber.ContractSupervisorGID.SupervisorManagerGID }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerPersonNumber.ContractSupervisorGID.SupervisorManagerGID createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipSupervisorManagerSupervisorManagerPersonNumberContractSupervisorGIDSupervisorManagerGID() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.SupervisorManager.SupervisorManagerPersonNumber.ContractSupervisorGID.SupervisorManagerGID();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.AssignmentSourceKeyBlock.AsgSourceKey }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.AssignmentSourceKeyBlock.AsgSourceKey createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerWorkRelationshipAssignmentSourceKeyBlockAsgSourceKey() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.WorkRelationship.AssignmentSourceKeyBlock.AsgSourceKey();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonInfoName.PersonName }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonInfoName.PersonName createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerPersonInfoNamePersonName() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonInfoName.PersonName();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonGID.PersonGIDDetails }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonGID.PersonGIDDetails createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerPersonGIDPersonGIDDetails() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonGID.PersonGIDDetails();
    }

    /**
     * Create an instance of {@link DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonInfoDetail.PersonInfoDetails }
     * 
     */
    public DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonInfoDetail.PersonInfoDetails createDATADSG1G2FILEFRAGMENTDPDHLINTCHRISSDH2SynchWorkerPersonInfoDetailPersonInfoDetails() {
        return new DATADS.G1 .G2 .FILEFRAGMENT.DPDHLINTCHRISSDH2Synch.Worker.PersonInfoDetail.PersonInfoDetails();
    }

}
