server.port=8083

info.app.name=DhlTalentLinkConnectorApp
spring.application.name=DhlTalentLinkConnectorApp
server.servlet.context-path=/dhltlkapi
server.tomcat.max-http-post-size=-1

logging.level.root=INFO
logging.level.xyz.dassiorleando.DhlTalentLinkConnectorApp=DEBUG

spring.speedment.logging=false
spring.speedment.url=jdbc:mysql://localhost:3307/?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
spring.speedment.username=root
spring.speedment.password=dhltlkprod2321
spring.speedment.schema=dhltalentlink-app

spring.mail.host=email-smtp.ap-south-1.amazonaws.com
spring.mail.username=AKIAXCUTAOQOSYV52QRC
spring.mail.password=BDlYu7erPzr/c8e7DrORevHJp7e+kWOhroEXM9OAfWjW
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
from.email.address=tlk-prod@atalent.me

#spring.cloud.azure.active-directory.enabled=true
#spring.cloud.azure.active-directory.credential.client-id=3512b28c-8bea-4bd8-bc8f-201a28d420b5
#spring.cloud.azure.active-directory.profile.tenant-id=c705971f-4b47-4829-9afe-35d1b38deb0d
#spring.cloud.azure.active-directory.app-id-uri=api://3512b28c-8bea-4bd8-bc8f-201a28d420b5

spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.credential.client-id=41c98fa4-ad47-41c7-a740-56a3a3a8fade
spring.cloud.azure.active-directory.profile.tenant-id=c705971f-4b47-4829-9afe-35d1b38deb0d
spring.cloud.azure.active-directory.app-id-uri=api://41c98fa4-ad47-41c7-a740-56a3a3a8fade


